name: daily-cron
on:
   schedule:
      - cron: "10 2 * * *"
jobs:
   cron:
      runs-on: ubuntu-latest
      steps:
         - name: Call our API route
           run: |
              curl --request GET \
              --url 'https://yoursite.com/api/messenger?message=hi po' \
