name: daily-cron
on:
   schedule:
      - cron: "50 2 * * *"
jobs:
   cron:
      runs-on: ubuntu-latest
      steps:
         - name: Call our API route
           run: |
              curl --request GET \
              --url 'https://automated-facebook-message.vercel.app/api/messenger?message=hi po' \
