name: morning
on:
   schedule:
      - cron: "5 12 * * *"
jobs:
   cron:
      runs-on: ubuntu-latest
      steps:
         - name: Call our API route
           run: |
              curl --request GET \
              --url 'https://peaceful-cove-89366.herokuapp.com/api/messenger?q=Good%20morning%20😊' \
